# Generated by Django 2.0.5 on 2018-05-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
