# Generated by Django 2.0.5 on 2018-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_Fav',
            field=models.BooleanField(default=False),
        ),
    ]
